name: circle_bottom_navigation
description: An animated, beauty and functional Bottom Navigation Bar you app.
version: 2.0.0
homepage: https://github.com/jeaanlucas/circle_bottom_navigation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
